1.

Условие:

ErrorCode answer = func(base, result, amountOfNums, 0.15, 3.4);

Вывод:

./main
Ошибка: введено неверное значение числа. Числа должны находиться в промежутке [0, 1]. 

2.

Условие:

int base = 0; // Основание

Вывод:

./main
Ошибка: введено некорректное основание системы счисления. 

3.

Условие:

long long amountOfNums = 2; // Количество чисел
int base = 10; // Основание
ErrorCode answer = func(base, result, amountOfNums, 3.0/7.0, 0.4);

Вывод:

./main
Предупреждение: число №1 содержит большое количество знаков после запятой. Результат может быть неверным. 
Функция выполнилась успешно. Результат:
Число №1 - не имеет конечное представление в системе счисления 10.
Число №2 - имеет конечное представление в системе счисления 10.

4.

Условие:

long long amountOfNums = 2; // Количество чисел
int base = 8; // Основание
ErrorCode answer = func(base, result, amountOfNums, 0.5, 0.75);

Вывод:

./main
Функция выполнилась успешно. Результат:
Число №1 - имеет конечное представление в системе счисления 8.
Число №2 - имеет конечное представление в системе счисления 8.

5.

Условие:

long long amountOfNums = 1; // Количество чисел
int base = 2; // Основание
ErrorCode answer = func(base, result, amountOfNums, 0.1);

Вывод:

./main
Функция выполнилась успешно. Результат:
Число №1 - не имеет конечное представление в системе счисления 2.
